import { FuturesAsset } from '../types/futures';

export const INITIAL_FUTURES_ASSETS: FuturesAsset[] = [
  // ==========================================
  // 1. CRYPTO FUTURES (20X Leverage)
  // ==========================================
  {
    id: 'fut_btc',
    name: 'Bitcoin (20X Futures)',
    symbol: 'BTC/USDT',
    tvSymbol: 'BINANCE:BTCUSDT',
    category: 'Crypto',
    price: 78370.00,
    change24h: -0.92,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_eth',
    name: 'Ethereum (20X Futures)',
    symbol: 'ETH/USDT',
    tvSymbol: 'BINANCE:ETHUSDT',
    category: 'Crypto',
    price: 2470.50,
    change24h: -0.78,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_sol',
    name: 'Solana (20X Futures)',
    symbol: 'SOL/USDT',
    tvSymbol: 'BINANCE:SOLUSDT',
    category: 'Crypto',
    price: 102.85,
    change24h: -0.90,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_bnb',
    name: 'Binance Coin (20X Futures)',
    symbol: 'BNB/USDT',
    tvSymbol: 'BINANCE:BNBUSDT',
    category: 'Crypto',
    price: 751.20,
    change24h: 1.50,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_xrp',
    name: 'Ripple (20X Futures)',
    symbol: 'XRP/USDT',
    tvSymbol: 'BINANCE:XRPUSDT',
    category: 'Crypto',
    price: 1.3995,
    change24h: 0.08,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 4,
    currencySymbol: '$',
  },
  {
    id: 'fut_doge',
    name: 'Dogecoin (20X Futures)',
    symbol: 'DOGE/USDT',
    tvSymbol: 'BINANCE:DOGEUSDT',
    category: 'Crypto',
    price: 0.08935,
    change24h: -1.25,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_ada',
    name: 'Cardano (20X Futures)',
    symbol: 'ADA/USDT',
    tvSymbol: 'BINANCE:ADAUSDT',
    category: 'Crypto',
    price: 0.7225,
    change24h: 0.45,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 4,
    currencySymbol: '$',
  },
  {
    id: 'fut_shib',
    name: 'Shiba Inu (20X Futures)',
    symbol: 'SHIB/USDT',
    tvSymbol: 'BINANCE:SHIBUSDT',
    category: 'Crypto',
    price: 0.00001850,
    change24h: -0.65,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 8,
    currencySymbol: '$',
  },
  {
    id: 'fut_pepe',
    name: 'Pepe Coin (20X Futures)',
    symbol: 'PEPE/USDT',
    tvSymbol: 'BINANCE:PEPEUSDT',
    category: 'Crypto',
    price: 0.00000980,
    change24h: 3.20,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 8,
    currencySymbol: '$',
  },
  {
    id: 'fut_ton',
    name: 'Toncoin (20X Futures)',
    symbol: 'TON/USDT',
    tvSymbol: 'BINANCE:TONUSDT',
    category: 'Crypto',
    price: 5.420,
    change24h: 0.95,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 3,
    currencySymbol: '$',
  },
  {
    id: 'fut_avax',
    name: 'Avalanche (20X Futures)',
    symbol: 'AVAX/USDT',
    tvSymbol: 'BINANCE:AVAXUSDT',
    category: 'Crypto',
    price: 28.90,
    change24h: -1.10,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_link',
    name: 'Chainlink (20X Futures)',
    symbol: 'LINK/USDT',
    tvSymbol: 'BINANCE:LINKUSDT',
    category: 'Crypto',
    price: 18.25,
    change24h: 0.85,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_sui',
    name: 'Sui Network (20X Futures)',
    symbol: 'SUI/USDT',
    tvSymbol: 'BINANCE:SUIUSDT',
    category: 'Crypto',
    price: 3.450,
    change24h: 4.80,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 3,
    currencySymbol: '$',
  },
  {
    id: 'fut_near',
    name: 'NEAR Protocol (20X Futures)',
    symbol: 'NEAR/USDT',
    tvSymbol: 'BINANCE:NEARUSDT',
    category: 'Crypto',
    price: 6.80,
    change24h: 2.15,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_apt',
    name: 'Aptos (20X Futures)',
    symbol: 'APT/USDT',
    tvSymbol: 'BINANCE:APTUSDT',
    category: 'Crypto',
    price: 9.85,
    change24h: 1.45,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_dot',
    name: 'Polkadot (20X Futures)',
    symbol: 'DOT/USDT',
    tvSymbol: 'BINANCE:DOTUSDT',
    category: 'Crypto',
    price: 8.20,
    change24h: -0.40,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_pol',
    name: 'Polygon Ecosystem (20X)',
    symbol: 'POL/USDT',
    tvSymbol: 'BINANCE:POLUSDT',
    category: 'Crypto',
    price: 0.4850,
    change24h: 0.65,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 4,
    currencySymbol: '$',
  },
  {
    id: 'fut_ltc',
    name: 'Litecoin (20X Futures)',
    symbol: 'LTC/USDT',
    tvSymbol: 'BINANCE:LTCUSDT',
    category: 'Crypto',
    price: 96.50,
    change24h: 1.10,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_bch',
    name: 'Bitcoin Cash (20X Futures)',
    symbol: 'BCH/USDT',
    tvSymbol: 'BINANCE:BCHUSDT',
    category: 'Crypto',
    price: 475.20,
    change24h: 0.75,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_trx',
    name: 'TRON (20X Futures)',
    symbol: 'TRX/USDT',
    tvSymbol: 'BINANCE:TRXUSDT',
    category: 'Crypto',
    price: 0.2150,
    change24h: 0.35,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 4,
    currencySymbol: '$',
  },
  {
    id: 'fut_uni',
    name: 'Uniswap (20X Futures)',
    symbol: 'UNI/USDT',
    tvSymbol: 'BINANCE:UNIUSDT',
    category: 'Crypto',
    price: 11.40,
    change24h: 2.80,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_render',
    name: 'Render Token (20X Futures)',
    symbol: 'RENDER/USDT',
    tvSymbol: 'BINANCE:RENDERUSDT',
    category: 'Crypto',
    price: 7.95,
    change24h: 3.40,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_fet',
    name: 'Artificial Superintelligence (20X)',
    symbol: 'FET/USDT',
    tvSymbol: 'BINANCE:FETUSDT',
    category: 'Crypto',
    price: 1.420,
    change24h: 2.90,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 3,
    currencySymbol: '$',
  },
  {
    id: 'fut_tao',
    name: 'Bittensor (20X Futures)',
    symbol: 'TAO/USDT',
    tvSymbol: 'BINANCE:TAOUSDT',
    category: 'Crypto',
    price: 485.00,
    change24h: 4.10,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },

  // ==========================================
  // 2. FOREX FUTURES (20X Leverage)
  // ==========================================
  {
    id: 'fut_eurusd',
    name: 'EUR / USD (20X Futures)',
    symbol: 'EUR/USD',
    tvSymbol: 'FX:EURUSD',
    category: 'Forex',
    price: 1.08450,
    change24h: 0.12,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_gbpusd',
    name: 'GBP / USD (20X Futures)',
    symbol: 'GBP/USD',
    tvSymbol: 'FX:GBPUSD',
    category: 'Forex',
    price: 1.29800,
    change24h: -0.18,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_usdjpy',
    name: 'USD / JPY (20X Futures)',
    symbol: 'USD/JPY',
    tvSymbol: 'FX:USDJPY',
    category: 'Forex',
    price: 153.800,
    change24h: 0.42,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 3,
    currencySymbol: '¥',
  },
  {
    id: 'fut_usdinr',
    name: 'USD / INR (20X Futures)',
    symbol: 'USD/INR',
    tvSymbol: 'FX_IDC:USDINR',
    category: 'Forex',
    price: 87.250,
    change24h: 0.04,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 3,
    currencySymbol: '₹',
  },
  {
    id: 'fut_audusd',
    name: 'AUD / USD (20X Futures)',
    symbol: 'AUD/USD',
    tvSymbol: 'FX:AUDUSD',
    category: 'Forex',
    price: 0.65400,
    change24h: -0.22,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_gbpjpy',
    name: 'GBP / JPY (20X Futures)',
    symbol: 'GBP/JPY',
    tvSymbol: 'FX:GBPJPY',
    category: 'Forex',
    price: 199.500,
    change24h: 0.28,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 3,
    currencySymbol: '¥',
  },
  {
    id: 'fut_usdcad',
    name: 'USD / CAD (20X Futures)',
    symbol: 'USD/CAD',
    tvSymbol: 'FX:USDCAD',
    category: 'Forex',
    price: 1.39200,
    change24h: 0.15,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_eurgbp',
    name: 'EUR / GBP (20X Futures)',
    symbol: 'EUR/GBP',
    tvSymbol: 'FX:EURGBP',
    category: 'Forex',
    price: 0.83500,
    change24h: 0.08,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 5,
    currencySymbol: '£',
  },
  {
    id: 'fut_eurjpy',
    name: 'EUR / JPY (20X Futures)',
    symbol: 'EUR/JPY',
    tvSymbol: 'FX:EURJPY',
    category: 'Forex',
    price: 166.800,
    change24h: 0.35,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 3,
    currencySymbol: '¥',
  },
  {
    id: 'fut_audcad',
    name: 'AUD / CAD (20X Futures)',
    symbol: 'AUD/CAD',
    tvSymbol: 'FX:AUDCAD',
    category: 'Forex',
    price: 0.91000,
    change24h: -0.11,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_nzdusd',
    name: 'NZD / USD (20X Futures)',
    symbol: 'NZD/USD',
    tvSymbol: 'FX:NZDUSD',
    category: 'Forex',
    price: 0.58900,
    change24h: -0.25,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_usdchf',
    name: 'USD / CHF (20X Futures)',
    symbol: 'USD/CHF',
    tvSymbol: 'FX:USDCHF',
    category: 'Forex',
    price: 0.88700,
    change24h: 0.09,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 5,
    currencySymbol: 'Fr',
  },
  {
    id: 'fut_euraud',
    name: 'EUR / AUD (20X Futures)',
    symbol: 'EUR/AUD',
    tvSymbol: 'FX:EURAUD',
    category: 'Forex',
    price: 1.63200,
    change24h: 0.22,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_gbpcad',
    name: 'GBP / CAD (20X Futures)',
    symbol: 'GBP/CAD',
    tvSymbol: 'FX:GBPCAD',
    category: 'Forex',
    price: 1.76500,
    change24h: -0.05,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_audjpy',
    name: 'AUD / JPY (20X Futures)',
    symbol: 'AUD/JPY',
    tvSymbol: 'FX:AUDJPY',
    category: 'Forex',
    price: 101.450,
    change24h: 0.18,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 3,
    currencySymbol: '¥',
  },
  {
    id: 'fut_cadjpy',
    name: 'CAD / JPY (20X Futures)',
    symbol: 'CAD/JPY',
    tvSymbol: 'FX:CADJPY',
    category: 'Forex',
    price: 112.350,
    change24h: 0.26,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 3,
    currencySymbol: '¥',
  },
  {
    id: 'fut_eurchf',
    name: 'EUR / CHF (20X Futures)',
    symbol: 'EUR/CHF',
    tvSymbol: 'FX:EURCHF',
    category: 'Forex',
    price: 0.94200,
    change24h: 0.05,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 5,
    currencySymbol: 'Fr',
  },
  {
    id: 'fut_usdmxn',
    name: 'USD / MXN (20X Futures)',
    symbol: 'USD/MXN',
    tvSymbol: 'FX:USDMXN',
    category: 'Forex',
    price: 18.254,
    change24h: -0.32,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 4,
    currencySymbol: '$',
  },
  {
    id: 'fut_usdbrl',
    name: 'USD / BRL (20X Futures)',
    symbol: 'USD/BRL',
    tvSymbol: 'FX:USDBRL',
    category: 'Forex',
    price: 5.482,
    change24h: 0.40,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 4,
    currencySymbol: 'R$',
  },
  {
    id: 'fut_eurthb',
    name: 'EUR / THB (20X Futures)',
    symbol: 'EUR/THB',
    tvSymbol: 'FX:EURTHB',
    category: 'Forex',
    price: 37.790,
    change24h: 0.15,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 3,
    currencySymbol: '฿',
  },

  // ==========================================
  // 3. US TITANS & TECH STOCKS (20X)
  // ==========================================
  {
    id: 'fut_nvda',
    name: 'NVIDIA (20X Futures)',
    symbol: 'NVDA',
    tvSymbol: 'NASDAQ:NVDA',
    category: 'US Stocks',
    price: 128.45,
    change24h: 2.15,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_aapl',
    name: 'Apple Inc. (20X Futures)',
    symbol: 'AAPL',
    tvSymbol: 'NASDAQ:AAPL',
    category: 'US Stocks',
    price: 234.80,
    change24h: 0.65,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_tsla',
    name: 'Tesla (20X Futures)',
    symbol: 'TSLA',
    tvSymbol: 'NASDAQ:TSLA',
    category: 'US Stocks',
    price: 248.50,
    change24h: 3.40,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_msft',
    name: 'Microsoft (20X Futures)',
    symbol: 'MSFT',
    tvSymbol: 'NASDAQ:MSFT',
    category: 'US Stocks',
    price: 428.20,
    change24h: 0.45,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_amzn',
    name: 'Amazon (20X Futures)',
    symbol: 'AMZN',
    tvSymbol: 'NASDAQ:AMZN',
    category: 'US Stocks',
    price: 186.75,
    change24h: 1.15,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_meta',
    name: 'Meta Platforms (20X Futures)',
    symbol: 'META',
    tvSymbol: 'NASDAQ:META',
    category: 'US Stocks',
    price: 585.40,
    change24h: 1.85,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_googl',
    name: 'Alphabet Google (20X)',
    symbol: 'GOOGL',
    tvSymbol: 'NASDAQ:GOOGL',
    category: 'US Stocks',
    price: 179.30,
    change24h: 0.72,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_amd',
    name: 'AMD Inc. (20X Futures)',
    symbol: 'AMD',
    tvSymbol: 'NASDAQ:AMD',
    category: 'US Stocks',
    price: 138.50,
    change24h: 2.30,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_intc',
    name: 'Intel Corp (20X Futures)',
    symbol: 'INTC',
    tvSymbol: 'NASDAQ:INTC',
    category: 'US Stocks',
    price: 24.15,
    change24h: -1.20,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_nflx',
    name: 'Netflix (20X Futures)',
    symbol: 'NFLX',
    tvSymbol: 'NASDAQ:NFLX',
    category: 'US Stocks',
    price: 672.10,
    change24h: 1.60,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_coin',
    name: 'Coinbase Global (20X)',
    symbol: 'COIN',
    tvSymbol: 'NASDAQ:COIN',
    category: 'US Stocks',
    price: 208.50,
    change24h: 4.25,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_pltr',
    name: 'Palantir Tech (20X Futures)',
    symbol: 'PLTR',
    tvSymbol: 'NASDAQ:PLTR',
    category: 'US Stocks',
    price: 37.80,
    change24h: 3.10,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_baba',
    name: 'Alibaba Group (20X)',
    symbol: 'BABA',
    tvSymbol: 'NYSE:BABA',
    category: 'US Stocks',
    price: 84.30,
    change24h: 1.40,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },

  // ==========================================
  // 4. INDIAN TITANS & INDICES (20X)
  // ==========================================
  {
    id: 'fut_nifty',
    name: 'NIFTY 50 Index (20X)',
    symbol: 'NIFTY 50',
    tvSymbol: 'NSE:NIFTY',
    category: 'Indian',
    price: 24850.00,
    change24h: 0.55,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_banknifty',
    name: 'BANK NIFTY Index (20X)',
    symbol: 'BANK NIFTY',
    tvSymbol: 'NSE:BANKNIFTY',
    category: 'Indian',
    price: 52350.00,
    change24h: 0.82,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_reliance',
    name: 'Reliance Industries (20X)',
    symbol: 'RELIANCE',
    tvSymbol: 'NSE:RELIANCE',
    category: 'Indian',
    price: 2890.00,
    change24h: 0.35,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_tatamotors',
    name: 'Tata Motors (20X Futures)',
    symbol: 'TATAMOTORS',
    tvSymbol: 'NSE:TATAMOTORS',
    category: 'Indian',
    price: 955.40,
    change24h: 1.15,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_hdfcbank',
    name: 'HDFC Bank (20X Futures)',
    symbol: 'HDFCBANK',
    tvSymbol: 'NSE:HDFCBANK',
    category: 'Indian',
    price: 1740.00,
    change24h: 0.45,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_infosys',
    name: 'Infosys (20X Futures)',
    symbol: 'INFY',
    tvSymbol: 'NSE:INFY',
    category: 'Indian',
    price: 1865.00,
    change24h: 0.90,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_sbi',
    name: 'State Bank of India (20X)',
    symbol: 'SBIN',
    tvSymbol: 'NSE:SBIN',
    category: 'Indian',
    price: 815.00,
    change24h: 0.60,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_icicibank',
    name: 'ICICI Bank (20X Futures)',
    symbol: 'ICICIBANK',
    tvSymbol: 'NSE:ICICIBANK',
    category: 'Indian',
    price: 1245.00,
    change24h: 0.75,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_tcs',
    name: 'Tata Consultancy Services (20X)',
    symbol: 'TCS',
    tvSymbol: 'NSE:TCS',
    category: 'Indian',
    price: 4150.00,
    change24h: 0.85,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_itc',
    name: 'ITC Limited (20X Futures)',
    symbol: 'ITC',
    tvSymbol: 'NSE:ITC',
    category: 'Indian',
    price: 485.20,
    change24h: 0.30,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_bhartiairtel',
    name: 'Bharti Airtel (20X Futures)',
    symbol: 'BHARTIARTL',
    tvSymbol: 'NSE:BHARTIARTL',
    category: 'Indian',
    price: 1680.00,
    change24h: 1.25,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_lt',
    name: 'Larsen & Toubro (20X)',
    symbol: 'LT',
    tvSymbol: 'NSE:LT',
    category: 'Indian',
    price: 3620.00,
    change24h: 0.70,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_maruti',
    name: 'Maruti Suzuki (20X Futures)',
    symbol: 'MARUTI',
    tvSymbol: 'NSE:MARUTI',
    category: 'Indian',
    price: 12450.00,
    change24h: 0.40,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },

  // ==========================================
  // 5. COMMODITIES & METALS (20X)
  // ==========================================
  {
    id: 'fut_gold',
    name: 'Gold Spot (20X Futures)',
    symbol: 'GOLD',
    tvSymbol: 'TVC:GOLD',
    category: 'Commodities',
    price: 2735.50,
    change24h: 0.85,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_silver',
    name: 'Silver Spot (20X Futures)',
    symbol: 'SILVER',
    tvSymbol: 'TVC:SILVER',
    category: 'Commodities',
    price: 33.700,
    change24h: 1.12,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 3,
    currencySymbol: '$',
  },
  {
    id: 'fut_crude',
    name: 'Crude Oil (WTI - 20X)',
    symbol: 'CRUDEOIL',
    tvSymbol: 'NYMEX:CL1!',
    category: 'Commodities',
    price: 74.20,
    change24h: -0.45,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_brent',
    name: 'Brent Crude Oil (20X)',
    symbol: 'BRENT',
    tvSymbol: 'TVC:UKOIL',
    category: 'Commodities',
    price: 78.45,
    change24h: -0.38,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_natgas',
    name: 'Natural Gas (20X)',
    symbol: 'NATGAS',
    tvSymbol: 'NYMEX:NG1!',
    category: 'Commodities',
    price: 2.840,
    change24h: 2.15,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 3,
    currencySymbol: '$',
  },
  {
    id: 'fut_copper',
    name: 'Copper (20X Futures)',
    symbol: 'COPPER',
    tvSymbol: 'COMEX:HG1!',
    category: 'Commodities',
    price: 4.380,
    change24h: 0.72,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 3,
    currencySymbol: '$',
  },
  {
    id: 'fut_platinum',
    name: 'Platinum Spot (20X)',
    symbol: 'PLATINUM',
    tvSymbol: 'TVC:PLATINUM',
    category: 'Commodities',
    price: 985.00,
    change24h: 0.65,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_aluminum',
    name: 'Aluminum Futures (20X)',
    symbol: 'ALUMINUM',
    tvSymbol: 'TVC:ALUMINUM',
    category: 'Commodities',
    price: 2580.00,
    change24h: -0.25,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
];
